# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :test do
  run_tests(scheme: "Friendly Competitions")
end

lane :deploy do
  setup_ci
  match(type: "appstore", readonly: is_ci)
  build_app(
    scheme: "Friendly Competitions", 
    include_bitcode: true
  )
  upload_to_app_store(
    force: true
  )
end