extension String {

    static var anonymousName: String {
        let randomAnimal = animals.randomElement()!
        return "Anonymous \(randomAnimal)"
    }

    private static var animals = [
        "Aardvark",
        "Alligator",
        "Alpaca",
        "Anaconda",
        "Ant",
        "Anteater",
        "Antelope",
        "Aphid",
        "Armadillo",
        "Asp",
        "Ass",
        "Baboon",
        "Badger",
        "Bald Eagle",
        "Barracuda",
        "Bass",
        "Basset Hound",
        "Bat",
        "Bearded Dragon",
        "Beaver",
        "Bedbug",
        "Bee",
        "Bee-eater",
        "Bird",
        "Bison",
        "Black panther",
        "Black Widow Spider",
        "Blue Jay",
        "Blue Whale",
        "Bobcat",
        "Buffalo",
        "Butterfly",
        "Buzzard",
        "Camel",
        "Canada Lynx",
        "Carp",
        "Cat",
        "Caterpillar",
        "Catfish",
        "Cheetah",
        "Chicken",
        "Chimpanzee",
        "Chipmunk",
        "Cobra",
        "Cod",
        "Condor",
        "Cougar",
        "Cow",
        "Coyote",
        "Crab",
        "Crane Fly",
        "Cricket",
        "Crocodile",
        "Crow",
        "Cuckoo",
        "Deer",
        "Dinosaur",
        "Dog",
        "Dolphin",
        "Donkey",
        "Dove",
        "Dragonfly",
        "Duck",
        "Eagle",
        "Eel",
        "Elephant",
        "Emu",
        "Falcon",
        "Ferret",
        "Finch",
        "Fish",
        "Flamingo",
        "Flea",
        "Fly",
        "Fox",
        "Frog",
        "Goat",
        "Goose",
        "Gopher",
        "Gorilla",
        "Guinea Pig",
        "Hamster",
        "Hare",
        "Hawk",
        "Hippopotamus",
        "Horse",
        "Hummingbird",
        "Humpback Whale",
        "Husky",
        "Iguana",
        "Impala",
        "Kangaroo",
        "Lemur",
        "Leopard",
        "Lion",
        "Lizard",
        "Llama",
        "Lobster",
        "Manatee",
        "Margay",
        "Monitor lizard",
        "Monkey",
        "Moose",
        "Mosquito",
        "Moth",
        "Mountain Zebra",
        "Mouse",
        "Mule",
        "Octopus",
        "Orca",
        "Ostrich",
        "Otter",
        "Owl",
        "Ox",
        "Oyster",
        "Panda",
        "Parrot",
        "Peacock",
        "Pelican",
        "Penguin",
        "Perch",
        "Pheasant",
        "Pig",
        "Pigeon",
        "Polar bear",
        "Porcupine",
        "Quagga",
        "Rabbit",
        "Raccoon",
        "Rat",
        "Rattlesnake",
        "Red Wolf",
        "Rooster",
        "Seal",
        "Sheep",
        "Skunk",
        "Sloth",
        "Snail",
        "Snake",
        "Spider",
        "Tiger",
        "Whale",
        "Wolf",
        "Wombat",
        "Zebra"
    ]
}
