name: Deploy to AppStore Connect

on:
  release:
    types: [published]

jobs:
  build:
    name: Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Homebrew
        run: brew bundle
      - name: Deploy
        run: fastlane release