name: Deploy to AppStore Connect

on:
  release:
    types: [published]

jobs:
  build:
    name: Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Homebrew
        run: brew bundle
      - name: Setup GoogleService-Info.plist
        run: echo $GOOGLE_SERVICE_INFO_RELEASE >> "Friendly Competitions/Firebase/Release/GoogleService-Info.plist"
        env:
          GOOGLE_SERVICE_INFO_RELEASE: ${{ secrets.GOOGLE_SERVICE_INFO_RELEASE }}
      - name: Deploy
        run: fastlane release
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}