name: Deploy to AppStore Connect

on:
  release:
    types: [published]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: macos-12
    steps:
    - uses: ./github/actions/setup/action.yml
      with:
        configuration: release

    # https://docs.fastlane.tools/getting-started/ios/authentication/
    - name: Deploy
      run: bundle exec fastlane deploy
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120