name: Deploy to AppStore Connect

on:
  release:
    types: [published]

jobs:
  build:
    name: Deploy
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GoogleService-Info.plist
        run: |
          mkdir -p "Friendly Competitions/Firebase/Release"
          echo $GOOGLE_SERVICE_INFO_RELEASE > "Friendly Competitions/Firebase/Release/GoogleService-Info.plist"
        env:
          GOOGLE_SERVICE_INFO_RELEASE: ${{ secrets.GOOGLE_SERVICE_INFO_RELEASE }}
      - name: Setup AppStore Connect API Key
        run: echo $APP_STORE_CONNECT_API_KEY > app_store_connect_api_key.p8
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      - name: Homebrew
        run: brew bundle

      # https://docs.fastlane.tools/getting-started/ios/authentication/
      - name: Deploy
        run: fastlane deploy
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}