name: Deploy to AppStore Connect

on:
  release:
    types: [published]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Deploy
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags.

    - name: Cache Ruby Gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-

    - name: Bundle Install
      run: |
        eval "$(rbenv init -)"
        bundle config --global jobs 4
        bundle config path vendor/bundle
        bundle install

    - name: Setup GoogleService-Info.plist
      run: |
        mkdir -p "Friendly Competitions/Firebase/Release"
        echo $GOOGLE_SERVICE_INFO_RELEASE > "Friendly Competitions/Firebase/Release/GoogleService-Info.plist"
      env:
        GOOGLE_SERVICE_INFO_RELEASE: ${{ secrets.GOOGLE_SERVICE_INFO_RELEASE }}

    - name: Homebrew
      run: brew bundle

    # https://docs.fastlane.tools/getting-started/ios/authentication/
    - name: Deploy
      run: fastlane deploy
      env:
        APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
        APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

    - uses: actions/upload-artifact@v3
      with:
        path: "Friendly Competitions.app.dSYM.zip"