name: Run unit tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore build cache
        uses: mikehardy/buildcache-action@v1
      - name: Homebrew
        run: brew bundle
      - name: Setup GoogleService-Info.plist
        run: |
          echo $GOOGLE_SERVICE_INFO_DEBUG > "Friendly Competitions/Firebase/Release/GoogleService-Info.plist"
        env:
          GOOGLE_SERVICE_INFO_DEBUG: ${{ secrets.GOOGLE_SERVICE_INFO_DEBUG }}
      - name: Test
        run: fastlane test