name: Run unit tests

on:
  pull_request:
    branches: [main]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: macos-12
    steps:
    - uses: ./github/actions/setup.yml
      with:
        configuration: debug
    - name: Fastlane
      run: bundle exec fastlane test
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120