name: Run unit tests

on:
  pull_request:
    branches: [main, release/*]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test
    runs-on: macos-13
    env:
      BUILDCACHE_DEBUG: 2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
  
    - name: Build Cache
      uses: mikehardy/buildcache-action@v2
    
    - name: Cache Swift Packages
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup GoogleService-Info.plist
      run: |
        mkdir -p "Friendly Competitions/Firebase/Debug"
        echo $GOOGLE_SERVICE_INFO_DEBUG > "Friendly Competitions/Firebase/Debug/GoogleService-Info.plist"
      env:
        GOOGLE_SERVICE_INFO_DEBUG: ${{ secrets.GOOGLE_SERVICE_INFO_DEBUG }}

    - name: Homebrew
      run: brew bundle
    
    - name: Fastlane
      run: bundle exec fastlane test
      env:
        CC: "clang" 
        CPLUSPLUS: "clang++" 
        LD: "clang" 
        LDPLUSPLUS: "clang++"
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120