name: Run unit tests

on:
  pull_request:
    branches: [ main, release/* ]

jobs:
  build:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore build cache
        uses: mikehardy/buildcache-action@v1
      - name: Homebrew
        run: brew bundle
      - name: Setup GoogleService-Info.plist
        run: |
          GOOGLE_SERVICE_INFO="Friendly Competitions/Firebase/Debug/GoogleService-Info.plist"
          touch GOOGLE_SERVICE_INFO
          echo $GOOGLE_SERVICE_INFO_DEBUG > GOOGLE_SERVICE_INFO
        env:
          GOOGLE_SERVICE_INFO_DEBUG: ${{ secrets.GOOGLE_SERVICE_INFO_DEBUG }}
      - name: Test
        run: fastlane test