name: Run unit tests

on:
  pull_request:
    branches: [main, release/*]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test
    runs-on: macos-12

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags.

    - name: Cache Ruby Gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ hashFiles('.ruby-version') }}-

    - name: Bundle Install
      run: |
        eval "$(rbenv init -)"
        bundle config --global jobs 4
        bundle config path vendor/bundle
        bundle install

    - name: Setup GoogleService-Info.plist
      run: |
        mkdir -p "Friendly Competitions/Firebase/Debug"
        echo $GOOGLE_SERVICE_INFO_DEBUG > "Friendly Competitions/Firebase/Debug/GoogleService-Info.plist"
      env:
        GOOGLE_SERVICE_INFO_DEBUG: ${{ secrets.GOOGLE_SERVICE_INFO_DEBUG }}

    - name: Homebrew
      run: brew bundle

    - name: Fastlane
      run: |
        bundle exec fastlane test