name: Run unit tests

on:
  pull_request:
    branches: [main]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    secrets: inherit
  test:
    name: Test
    runs-on: macos-12
    steps:
    - name: Fastlane
      run: bundle exec fastlane test
      env:
        FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120