name: Run unit tests

on:
  pull_request:
    branches: [main, release/*]

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Test
    runs-on: macos-12

    steps:
      steps:
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_KEY }} 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore build cache
        uses: mikehardy/buildcache-action@v1

      - name: Setup GoogleService-Info.plist
        run: |
          mkdir -p "Friendly Competitions/Firebase/Debug"
          echo $GOOGLE_SERVICE_INFO_DEBUG > "Friendly Competitions/Firebase/Debug/GoogleService-Info.plist"
        env:
          GOOGLE_SERVICE_INFO_DEBUG: ${{ secrets.GOOGLE_SERVICE_INFO_DEBUG }}

      - name: Homebrew
        run: brew bundle

      - name: Test
        run: fastlane test