name: Run unit tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Unit tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore build cache
        uses: mikehardy/buildcache-action@v1
      - name: Homebrew
        run: brew bundle
      - name: Build & upload iOS binary
        run: bundle exec fastlane test